name: Pull Request SideStore build
on:
  pull_request:

jobs:
  build:
    name: Build and upload SideStore
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'macos-12'
            version: '14.2'

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: brew install ldid

      - name: Add PR suffix to version
        run: sed -e "/MARKETING_VERSION = .*/s/\$/-pr.${{ github.event.pull_request.number }}+$(git rev-parse --short HEAD)/" -i '' Build.xcconfig

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: ${{ matrix.version }}

      - name: Build SideStore
        run: make build | xcpretty && exit ${PIPESTATUS[0]}

      - name: Fakesign app
        run: make fakesign

      - name: Convert to IPA
        run: make ipa

      - name: Upload SideStore.ipa Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: SideStore.ipa
          path: SideStore.ipa

      - name: Upload *.dSYM Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: SideStore-dSYM
          path: ./*.dSYM/
