name: Stable SideStore build
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    name: Build and upload SideStore
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'macos-12'
            version: '14.2'

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: brew install ldid

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: ${{ matrix.version }}

      - name: Build SideStore
        run: |
          xcodebuild -project AltStore.xcodeproj \
          -scheme AltStore \
          -sdk iphoneos \
          archive -archivePath ./archive \
          CODE_SIGNING_REQUIRED=NO \
          AD_HOC_CODE_SIGNING_ALLOWED=YES \
          CODE_SIGNING_ALLOWED=NO \
          DEVELOPMENT_TEAM=XYZ0123456 \
          ORG_IDENTIFIER=com.SideStore \
          | xcpretty && exit ${PIPESTATUS[0]}

      - name: Fakesign app
        run: |
          rm -rf archive.xcarchive/Products/Applications/SideStore.app/Frameworks/AltStoreCore.framework/Frameworks/
          ldid -SAltStore/Resources/tempEnt.plist archive.xcarchive/Products/Applications/SideStore.app/SideStore

      - name: Convert to IPA
        run: |
          mkdir Payload
          mkdir Payload/SideStore.app
          cp -R archive.xcarchive/Products/Applications/SideStore.app/ Payload/SideStore.app/
          zip -r SideStore.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: SideStore.ipa
          path: SideStore.ipa

      - name: Get version
        id: version
        run: echo "version=$(grep MARKETING_VERSION Build.xcconfig | sed -e "s/MARKETING_VERSION = //g")" >> $GITHUB_OUTPUT

      - name: Get current date
        id: date
        run: echo "date=$(date -u +'%c')" >> $GITHUB_OUTPUT

      - name: Get current date in AltStore date form
        id: date_altstore
        run: echo "date=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Upload to new stable release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          draft: true
          files: SideStore.ipa
          body: |
            ## Changelog
            
            - TODO
            
            ## Build Info
            
            Built at (UTC): `${{ steps.date.outputs.date }}`
            Built at (UTC date): `${{ steps.date_altstore.outputs.date }}`
            Commit SHA: `${{ github.sha }}`
            Version: `${{ steps.version.outputs.version }}`
